# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for deploying Azure Machine Learning endpoints: real-time (webservices) or batch (pipelines)

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspace
  type: string
- name: deploymentScript
  type: string
- name: scriptArguments
  type: string
- name: jobName
  type: string
  default: 'deploy'
- name: jobDisplayName
  type: string
  default: 'Deploy Endpoint'
- name: dependsOn
  type: object
  default: []
- name: artifactName
  type: string
  default: ''
- name: createArtifact
  type: string
  default: false

jobs:

- job: artifact_setup
  displayName: 'Artifact setup'
  dependsOn: ${{parameters.dependsOn}}
  steps:

    - bash: |
        if [ "${{parameters.artifactName}}" == "" ]; then
          artifact_name='DeploymentCodeInternalArtifact'
        else
          artifact_name=${{parameters.artifactName}}
        fi
        echo "Artifact name: $artifact_name"
        echo "##vso[task.setvariable variable=artifact_name;isOutput=true;]$artifact_name"
      name: set_artifact_name
      displayName: 'Set artifact name'
      failOnStderr: true

    - ${{ if eq(parameters.createArtifact, 'true') }}:
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: '$(set_artifact_name.artifact_name)'
          targetPath: '$(Build.SourcesDirectory)'
        name: build_code
        displayName: 'Build code to deploy'

- deployment: ${{parameters.jobName}}
  displayName: ${{parameters.jobDisplayName}}
  dependsOn: artifact_setup
  variables:
      artifact_name: $[ dependencies.artifact_setup.outputs['set_artifact_name.artifact_name'] ]
  pool:
    vmImage: $(VM_VERSION)
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:

          - task: DownloadPipelineArtifact@2
            displayName: 'Download deployment code'
            inputs:
              artifact: '$(ARTIFACT_NAME)'
              path: $(System.ArtifactsDirectory)/deploymentcode/

          - template: run-aml-python-code.template.yml
            parameters:
              serviceConnection: ${{parameters.serviceConnection}}
              resourceGroup: ${{parameters.resourceGroup}}
              amlWorkspace: ${{parameters.amlWorkspace}}
              scriptPath: $(System.ArtifactsDirectory)/deploymentcode/${{parameters.deploymentScript}}
              scriptArguments: ${{parameters.scriptArguments}}
              scriptExtraDependencies: pyyaml
